In [4]:
a=3 #for new cell alt+enter;

In [5]:
a=7

In [6]:
print(a)

7


In [7]:
print(id(a)) #for address of a;

140734567527440


In [10]:
# prints all the keyword
import keyword
print(keyword.kwlist)
print('\n')
print("total number of keywords ",len(keyword.kwlist))

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


total number of keywords  35


In [11]:
x=1
y="tsm"

In [13]:
type(x)
#type(y)

int

# Numeric Operation

In [14]:
a=10
b=20
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a // b)  # return floor division;
print(a % b)   # return remainder;
print(a ** b)  #return 10 power 20;

30
-10
200
0.5
0
10
100000000000000000000


In [15]:
a=9
a+=1
print(a)
a-=1
print(a)

10
9


In [16]:
import math
x=2
math.log(x)

0.6931471805599453

# Numpy

In [2]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
arr=np.array([[1,2,3],
             [4,5,6]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(2, 3)

In [51]:
arr.ndim   #return dimension of array

2

In [53]:
len(arr)   # returns the size of the first dimensionthe size of the first dimension

2

In [9]:
arr.dtype

dtype('int32')

In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [39]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# numpy is fast

In [15]:
import time
import sys
c=range(10000)

In [16]:
%timeit [i**3 for i in c]

2.99 ms ± 22.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
c_numpy=np.arange(10000)

In [20]:
%timeit c_numpy**3

16.5 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [22]:
l1=range(10000)
l2=[i**2 for i in range(10000)]

In [23]:
%timeit list(map(lambda x,y:x*y,l1,l2))

1.02 ms ± 6.26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [24]:
a1=np.array(l1)
a2=np.array(l2)

In [38]:
%timeit a1*a2

7.53 µs ± 65.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# common arrays

In [28]:
np.arange(2,13,2)

array([ 2,  4,  6,  8, 10, 12])

In [30]:
np.zeros((3,2))    #remainde tuples

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.eye(3)   #square matrix for eye functn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [36]:
np.full((3,3),2.2, dtype=np.int64)   #datatpe forced to int.

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [37]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
v= np.array([1,2,3])

In [41]:
v

array([1, 2, 3])

In [42]:
np.tile(v,(3,1))   # 3 rows 1 col

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
np.random.random()

0.725084439981606

In [49]:
50*np.random.random()+2

10.136345945669255

In [50]:
np.random.random([3,3])

array([[0.08156475, 0.63656065, 0.68118487],
       [0.81060281, 0.79415403, 0.78758474],
       [0.37958838, 0.32323208, 0.27096184]])

In [57]:
e=np.linspace(1,50,10) # i want number from 1 to 50 with 10 parts.

In [58]:
e

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [59]:
e.itemsize   # 8bytes memory taken

8

In [60]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [3]:
np.arange(18).shape

(18,)

In [7]:
b=np.arange(18).reshape(2,3,3)
print(b)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
3


In [65]:
b.shape

(2, 3, 3)

In [10]:
 np.arange(18).reshape(2,3,-1)  #-1 will automaticallly make it

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [67]:
a=np.array([2,4,6,8,10,12,14,16])

In [68]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [69]:
a[2]

6

In [71]:
a[[2,4,6]]

array([ 6, 10, 14])

In [73]:
a[::2]

array([ 2,  6, 10, 14])

In [74]:
b=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [75]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
b[2,2]

9

In [78]:
b>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [80]:
b[(b>2) & (b<5)]

array([3, 4])

In [81]:
a=np.arange(10)

In [82]:
b=a  #it doesnt create new memory both a and b are pointing to same location

In [83]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
b[0]=11

In [85]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [86]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [87]:
np.shares_memory(a,b)  #to check if both are pointing to same location

True

In [88]:
a=np.arange(10)

In [89]:
b=a.copy()

In [90]:
b[0]=11

In [91]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [92]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.shares_memory(a,b)

False

In [94]:
a=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [95]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
a.T    #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [97]:
b=np.array([[11,12,13],
          [14,15,16],
          [17,18,19]])

In [98]:
a==b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [99]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [100]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [101]:
 a=np.arange(1,10)

In [102]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [103]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [104]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.sum(a)

45

In [106]:
np.median(a)

5.0

In [107]:
np.std(a)

2.581988897471611

In [116]:
f=np.arange(1,10).reshape(3,3)

In [117]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
np.linalg.det(f)

0.0

In [123]:
from numpy.linalg import inv
inv(f)

LinAlgError: Singular matrix

In [120]:
np.linalg.eig(f)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [124]:
b=f.T

In [125]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [126]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
np.dot(f,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [129]:
a=np.array([1,1,0],dtype=bool)
b=np.array([1,0,1],dtype=bool)

In [130]:
np.logical_or(a,b)

array([ True,  True,  True])

In [131]:
np.logical_and(a,b)

array([ True, False, False])

In [133]:
np.all(a==b)

False

In [134]:
a=np.array([[1,2],
            [3,4]])

In [135]:
a.sum()

10

In [136]:
a.sum(axis=0)

array([4, 6])

In [137]:
a.sum(axis=1)

array([3, 7])

In [138]:
a.max()

4

In [139]:
a.argmax()

3

In [140]:
a.shape

(2, 2)

In [143]:
a=np.arange(1,10)

In [144]:
a.shape

(9,)

In [145]:
a[:,np.newaxis].shape

(9, 1)

In [146]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Pandas

In [1]:
import pandas as pd

In [5]:
a = pd.Series([1,2,3,4,5])

In [6]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
type(a)

pandas.core.series.Series

In [9]:
a[2]

3

In [10]:
b = pd.Series(['a', 'b', 'c'])

In [11]:
b

0    a
1    b
2    c
dtype: object

In [13]:
a = pd.date_range(start='01-01-2018', end='23-5-2018')

In [14]:
a

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17',
               '2018-05-18', '2018-05-19', '2018-05-20', '2018-05-21',
               '2018-05-22', '2018-05-23'],
              dtype='datetime64[ns]', length=143, freq='D')

In [15]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

# pandas dataframe

In [16]:
import numpy as np

In [19]:
temp= np.random.randint(low=20, high=100, size=[20,])
name= np.random.choice(['Tarun','Singh','Mahar','TSM'],20)
random= np.random.choice([10,11,12,13,14],20)

In [20]:
a= list(zip(temp,name,random))

In [24]:
df= pd.DataFrame(data=a,columns=['temp','name','random'])

In [25]:
df

temp   name  random
0     71  Mahar      12
1     45  Mahar      11
2     74  Singh      11
3     26  Mahar      11
4     77    TSM      11
5     27  Singh      10
6     61  Mahar      10
7     99  Tarun      11
8     56    TSM      14
9     36  Tarun      14
10    99  Tarun      14
11    72  Mahar      12
12    92  Tarun      12
13    26  Singh      10
14    57  Singh      12
15    96  Singh      10
16    78  Tarun      14
17    66  Singh      11
18    72  Mahar      13
19    71  Singh      11

In [29]:
type(df)

pandas.core.frame.DataFrame

# DataFrame using dictionaries

In [76]:
df = pd.DataFrame({'temp':temp, 'name':name, 'random':random}) 

In [77]:
type(df)

pandas.core.frame.DataFrame

In [78]:
df

temp   name  random
0     71  Mahar      12
1     45  Mahar      11
2     74  Singh      11
3     26  Mahar      11
4     77    TSM      11
5     27  Singh      10
6     61  Mahar      10
7     99  Tarun      11
8     56    TSM      14
9     36  Tarun      14
10    99  Tarun      14
11    72  Mahar      12
12    92  Tarun      12
13    26  Singh      10
14    57  Singh      12
15    96  Singh      10
16    78  Tarun      14
17    66  Singh      11
18    72  Mahar      13
19    71  Singh      11

In [79]:
df.head()

temp   name  random
0    71  Mahar      12
1    45  Mahar      11
2    74  Singh      11
3    26  Mahar      11
4    77    TSM      11

In [80]:
df.tail()

temp   name  random
15    96  Singh      10
16    78  Tarun      14
17    66  Singh      11
18    72  Mahar      13
19    71  Singh      11

In [81]:
df.shape

(20, 3)

In [82]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [83]:
df.name

0     Mahar
1     Mahar
2     Singh
3     Mahar
4       TSM
5     Singh
6     Mahar
7     Tarun
8       TSM
9     Tarun
10    Tarun
11    Mahar
12    Tarun
13    Singh
14    Singh
15    Singh
16    Tarun
17    Singh
18    Mahar
19    Singh
Name: name, dtype: object

In [84]:
#df['name']

In [85]:
df['temp'].describe()

count    20.000000
mean     65.050000
std      23.457633
min      26.000000
25%      53.250000
50%      71.000000
75%      77.250000
max      99.000000
Name: temp, dtype: float64

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp      20 non-null int32
name      20 non-null object
random    20 non-null int32
dtypes: int32(2), object(1)
memory usage: 400.0+ bytes


In [87]:
df.values

array([[71, 'Mahar', 12],
       [45, 'Mahar', 11],
       [74, 'Singh', 11],
       [26, 'Mahar', 11],
       [77, 'TSM', 11],
       [27, 'Singh', 10],
       [61, 'Mahar', 10],
       [99, 'Tarun', 11],
       [56, 'TSM', 14],
       [36, 'Tarun', 14],
       [99, 'Tarun', 14],
       [72, 'Mahar', 12],
       [92, 'Tarun', 12],
       [26, 'Singh', 10],
       [57, 'Singh', 12],
       [96, 'Singh', 10],
       [78, 'Tarun', 14],
       [66, 'Singh', 11],
       [72, 'Mahar', 13],
       [71, 'Singh', 11]], dtype=object)

In [88]:
df

temp   name  random
0     71  Mahar      12
1     45  Mahar      11
2     74  Singh      11
3     26  Mahar      11
4     77    TSM      11
5     27  Singh      10
6     61  Mahar      10
7     99  Tarun      11
8     56    TSM      14
9     36  Tarun      14
10    99  Tarun      14
11    72  Mahar      12
12    92  Tarun      12
13    26  Singh      10
14    57  Singh      12
15    96  Singh      10
16    78  Tarun      14
17    66  Singh      11
18    72  Mahar      13
19    71  Singh      11

In [97]:
df.set_index('temp',inplace= True)
 # inplace makes permanent change to dataframe

In [98]:
df

name  random
temp               
71    Mahar      12
45    Mahar      11
74    Singh      11
26    Mahar      11
77      TSM      11
27    Singh      10
61    Mahar      10
99    Tarun      11
56      TSM      14
36    Tarun      14
99    Tarun      14
72    Mahar      12
92    Tarun      12
26    Singh      10
57    Singh      12
96    Singh      10
78    Tarun      14
66    Singh      11
72    Mahar      13
71    Singh      11

In [99]:
df.sort_index(axis=0,ascending=False)

name  random
temp               
99    Tarun      14
99    Tarun      11
96    Singh      10
92    Tarun      12
78    Tarun      14
77      TSM      11
74    Singh      11
72    Mahar      12
72    Mahar      13
71    Mahar      12
71    Singh      11
66    Singh      11
61    Mahar      10
57    Singh      12
56      TSM      14
45    Mahar      11
36    Tarun      14
27    Singh      10
26    Singh      10
26    Mahar      11

In [100]:
df.sort_values(by='random')

name  random
temp               
27    Singh      10
61    Mahar      10
96    Singh      10
26    Singh      10
71    Singh      11
45    Mahar      11
74    Singh      11
26    Mahar      11
77      TSM      11
99    Tarun      11
66    Singh      11
57    Singh      12
71    Mahar      12
72    Mahar      12
92    Tarun      12
72    Mahar      13
99    Tarun      14
78    Tarun      14
56      TSM      14
36    Tarun      14

In [101]:
df.drop(['random'],axis=1)     
 # this is not permanent change if u want to make permanent change 
    #then use inplace is True'''
                               

name
temp       
71    Mahar
45    Mahar
74    Singh
26    Mahar
77      TSM
27    Singh
61    Mahar
99    Tarun
56      TSM
36    Tarun
99    Tarun
72    Mahar
92    Tarun
26    Singh
57    Singh
96    Singh
78    Tarun
66    Singh
72    Mahar
71    Singh

In [102]:
df

name  random
temp               
71    Mahar      12
45    Mahar      11
74    Singh      11
26    Mahar      11
77      TSM      11
27    Singh      10
61    Mahar      10
99    Tarun      11
56      TSM      14
36    Tarun      14
99    Tarun      14
72    Mahar      12
92    Tarun      12
26    Singh      10
57    Singh      12
96    Singh      10
78    Tarun      14
66    Singh      11
72    Mahar      13
71    Singh      11

In [103]:
df.head()

name  random
temp               
71    Mahar      12
45    Mahar      11
74    Singh      11
26    Mahar      11
77      TSM      11

In [108]:
df.iloc[[0,1,2]]

name  random
temp               
71    Mahar      12
45    Mahar      11
74    Singh      11

In [109]:
df.iloc[1:5,1]

temp
45    11
74    11
26    11
77    11
Name: random, dtype: int32

In [106]:
df.iloc[[True,True,False,True]]

name  random
temp               
71    Mahar      12
45    Mahar      11
26    Mahar      11

In [107]:
df.head()

name  random
temp               
71    Mahar      12
45    Mahar      11
74    Singh      11
26    Mahar      11
77      TSM      11

In [110]:
df.iloc[0,:]

name      Mahar
random       12
Name: 71, dtype: object

In [113]:
df.loc[45,:]
#here 45 is the index position

name      Mahar
random       11
Name: 45, dtype: object

In [116]:
df.loc[[71,45,74]]

name  random
temp               
71    Mahar      12
71    Singh      11
45    Mahar      11
74    Singh      11

In [117]:
df.tail()

name  random
temp               
96    Singh      10
78    Tarun      14
66    Singh      11
72    Mahar      13
71    Singh      11

In [122]:
df.loc[[96,78],'name':'random']

name  random
temp               
96    Singh      10
78    Tarun      14

In [123]:
df.head()

name  random
temp               
71    Mahar      12
45    Mahar      11
74    Singh      11
26    Mahar      11
77      TSM      11

In [121]:
df.loc[[True,True,False,True]]

name  random
temp               
71    Mahar      12
45    Mahar      11
26    Mahar      11

In [124]:
df.loc[df.random>13]

name  random
temp               
56      TSM      14
36    Tarun      14
99    Tarun      14
78    Tarun      14

In [125]:
df.loc[(df.random>13) | (df.random==10),:]

name  random
temp               
27    Singh      10
61    Mahar      10
56      TSM      14
36    Tarun      14
99    Tarun      14
26    Singh      10
96    Singh      10
78    Tarun      14

# Merge_and_Concat

In [127]:
d1=pd.DataFrame([['a',1],
                ['b',2]],columns=['col1','number'])
d2=pd.DataFrame([['c',3,'lion'],
                ['d',4,'tiger']],columns=['letter','number','animal'])

In [128]:
d1

col1  number
0    a       1
1    b       2

In [129]:
d2

letter  number animal
0      c       3   lion
1      d       4  tiger

In [133]:
pd.concat([d1,d2],axis=0)
#,sort=True

c:\users\tarun singh mahar\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
0   lion  NaN      c       3
1  tiger  NaN      d       4

In [134]:
pd.concat([d1,d2],axis=0,ignore_index=True)

c:\users\tarun singh mahar\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


animal col1 letter  number
0    NaN    a    NaN       1
1    NaN    b    NaN       2
2   lion  NaN      c       3
3  tiger  NaN      d       4

In [135]:
pd.concat([d1,d2],axis=1)

col1  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [136]:
d1= pd.DataFrame([['lucknow',32],
                 ['kanpur',45],
                 ['agra',30],
                 ['delhi',40]],columns=['city','temperature'])

In [137]:
d1

city  temperature
0  lucknow           32
1   kanpur           45
2     agra           30
3    delhi           40

In [138]:
#using dictionary
d2=pd.DataFrame({
    "city":["delhi","lucknow","kanpur"],
    "humidity":[68,65,75]
})

In [139]:
d2

city  humidity
0    delhi        68
1  lucknow        65
2   kanpur        75

In [140]:
df=pd.merge(d1,d2,on='city')

In [141]:
df

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68

In [146]:
pd.merge(d1,d2,on=['city'],how='outer')   
#outer for union

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [149]:
pd.merge(d1,d2,on=['city'],how='inner')
#inner for intersetion

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68

In [150]:
pd.merge(d1,d2,on=['city'],how='left')

city  temperature  humidity
0  lucknow           32      65.0
1   kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [151]:
pd.merge(d1,d2,on=['city'],how='right')

city  temperature  humidity
0  lucknow           32        65
1   kanpur           45        75
2    delhi           40        68